# 普通数据
name: 小明

# 对象数据
student:
  name: 小强
  age: 18

teacher: {name: 小李,age: 31,color: 红}

# Map数据

# 配置数组
city:
  - 北京
  - 上海
  - 天津
  - 重庆
country: [中,美,英,德,日]

# 集合
actor:
  - name: 小青
    age: 18
  - name: 小白
    age: 19
  - name: 小蓝
    age: 19

# springboot内置
server:
  port: 8081
